name: Pipeline

on: workflow-dispatch

runs-on: ubuntu@latest
steps:
  - uses: actions/checkout@v5
  - name: Set up JDK 11 for x64
    uses: actions/setup-java@v4
    with:
      java-version: '11'
      distribution: 'temurin'
      architecture: x64


steps:
  - uses: actions/checkout@v5
  - uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'temurin'
  - name: Run the Maven build
    run: mvn clean file.java

   run: mkdir jarfile && cp target/*.jar jarfile

  - uses: actions/upload-artifact@v4
    with:
      name: Package
      path: jarfile/

  
