#
# ==========================
#  TruffleHog3 Security Rules
#  Media Planning MCP Server
# ==========================
# 
# This file contains patterns for detecting potential secrets in code.
# 
# IMPORTANT: This file is automatically excluded from security scanning
# to prevent false positives from the detection patterns themselves.
#
# Rule Format:
# - id: unique.identifier
#   message: Human readable description
#   pattern: Regular expression pattern
#   severity: HIGH|MEDIUM|LOW
#
# For entropy-based rules:
# - alphabet: Character set to analyze
#   threshold: Entropy threshold (higher = more random)
#   minlen: Minimum string length
#

#
# ==========================
#  Entropy-Based Rules
# ==========================
#
- id: high-entropy-base64
  message: High Entropy (Base64-like)
  minlen: 20
  alphabet: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/="
  threshold: 4.5
  severity: MEDIUM

- id: high-entropy-hex
  message: High Entropy (Hex-like)
  minlen: 20
  alphabet: "0123456789abcdefABCDEF"
  threshold: 3.0
  severity: MEDIUM

#
# ==========================
#  Regex-Based Rules
# ==========================
#

# --- Default TruffleHog3 Rules ---
- id: private.pgp-key
  message: PGP Private Key Block
  pattern: "-----BEGIN PGP PRIVATE KEY BLOCK-----"
  severity: HIGH

- id: private.key
  message: Private Key
  pattern: "-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----"
  severity: HIGH

- id: amazon.aws-api-key
  message: AWS API Key
  pattern: "AKIA[0-9A-Z]{16}"
  severity: MEDIUM

- id: amazon.mws-auth-token
  message: Amazon MWS Auth Token
  pattern: "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
  severity: MEDIUM

- id: facebook.access-token
  message: Facebook Access Token
  pattern: "EAACEdEose0cBA[0-9A-Za-z]+"
  severity: MEDIUM

- id: facebook.oauth-token
  message: Facebook OAuth Token
  pattern: '[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*[''|"][0-9a-f]{32}[''|"]'
  severity: MEDIUM

- id: github.token
  message: GitHub Token
  pattern: '[g|G][i|I][t|T][h|H][u|U][b|B].*[''|"][0-9a-zA-Z]{35,40}[''|"]'
  severity: MEDIUM

- id: google.access-token
  message: Google Access Token
  pattern: "ya29\\.[0-9A-Za-z\\-_]+"
  severity: MEDIUM
  
- id: generic.email
  message: Generic email address
  pattern: "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}"
  severity: LOW

- id: google.api-key
  message: Google API Key
  pattern: "AIza[0-9A-Za-z\\-_]{35}"
  severity: MEDIUM

- id: google.oauth-token
  message: Google OAuth
  pattern: "[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com"
  severity: MEDIUM

- id: google.gcp-service-account
  message: Google Cloud Platform Service Account
  pattern: '"type": "service_account"'
  severity: MEDIUM

- id: heroku.api-key
  message: Heroku API Key
  pattern: "[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"
  severity: MEDIUM

- id: mailchimp.api-key
  message: MailChimp API Key
  pattern: "[0-9a-f]{32}-us[0-9]{1,2}"
  severity: MEDIUM

- id: mailgun.api-key
  message: Mailgun API Key
  pattern: "key-[0-9a-zA-Z]{32}"
  severity: MEDIUM

- id: paypal.braintree-access-token
  message: PayPal Braintree Access Token
  pattern: "access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}"
  severity: MEDIUM

- id: picatic.api-key
  message: Picatic API Key
  pattern: "sk_live_[0-9a-z]{32}"
  severity: MEDIUM

- id: slack.token
  message: Slack Token
  pattern: "xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32}"
  severity: MEDIUM

- id: slack.bot-token
  message: Slack Bot Token
  pattern: "xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[a-z0-9]{24}"
  severity: MEDIUM

- id: slack.webhook
  message: Slack Webhook
  pattern: "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
  severity: MEDIUM

- id: stripe.api-key
  message: Stripe API Key
  pattern: "sk_live_[0-9a-zA-Z]{24}"
  severity: MEDIUM

- id: stripe.restricted-api-key
  message: Stripe Restricted API Key
  pattern: "rk_live_[0-9a-zA-Z]{24}"
  severity: MEDIUM

- id: square.access-token
  message: Square Access Token
  pattern: "sq0atp-[0-9A-Za-z\\-_]{22}"
  severity: MEDIUM

- id: square.oauth-secret
  message: Square OAuth Secret
  pattern: "sq0csp-[0-9A-Za-z\\-_]{43}"
  severity: MEDIUM

- id: twilio.api-key
  message: Twilio API Key
  pattern: "SK[0-9a-fA-F]{32}"
  severity: MEDIUM

- id: twitter.access-token
  message: Twitter Access Token
  pattern: "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[1-9][0-9]+-[0-9a-zA-Z]{40}"
  severity: MEDIUM

- id: twitter.oauth-token
  message: Twitter OAuth Token
  pattern: '[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[''|"][0-9a-zA-Z]{35,44}[''|"]'
  severity: MEDIUM

- id: generic.api-key
  message: Generic API Key
  pattern: '[a|A][p|P][i|I][_]? [k|K][e|E][y|Y].*[''|"][0-9a-zA-Z]{32,45}[''|"]'
  severity: LOW

- id: generic.secret
  message: Generic Secret
  pattern: '[s|S][e|E][c|C][r|R][e|E][t|T].*[''|"][0-9a-zA-Z]{32,45}[''|"]'
  severity: LOW

- id: generic.password-in-url
  message: Password in URL
  pattern: "[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s]"
  severity: LOW

#
# ==========================
#  Custom Generalized Rules
# ==========================
#

- id: generic.password-assignment
  message: Password or secret assignment (generic)
  pattern: "(?i)\\b(?:password|pass|pwd|db_password|secret|api[_-]?key|apikey|auth[_-]?token|client[_-]?secret|access[_-]?token|token|cred|credential)\\s*[:=]\\s*['\"][^'\"]{4,}['\"]"
  severity: MEDIUM

- id: github.token.short
  message: GitHub Token (short or fake format)
  pattern: "(?i)ghp_[A-Za-z0-9]{8,}"
  severity: MEDIUM

- id: env-var-style.secret
  message: Environment variable style secrets
  pattern: "(?m)(?i)^(?:PASSWORD|PASS|PWD|SECRET|API_KEY|API-KEY|APIKEY|MONGODB_URI|SERPAPI_KEY|AUTH_TOKEN|ACCESS_TOKEN|CLIENT_SECRET|DB_PASSWORD|DB_PASS|MONGO_URI|MONGO_URL|CONNECTION_STRING|TOKEN|CREDENTIAL|PRIVATE_KEY)\\s*=\\s*([^\\n\\r]{4,})"
  severity: MEDIUM

- id: json.key.secret
  message: Secret in JSON key-value pair
  pattern: "(?i)\"(?:password|pass|pwd|secret|api[_-]?key|apikey|auth[_-]?token|client[_-]?secret|db[_-]?password|access[_-]?token|token|credential)\"\\s*:\\s*\"([^\\\"]{4,})\""
  severity: MEDIUM

- id: function.argument.secret
  message: Secret or token passed as function argument
  pattern: "(?i)\\w+\\([^)]*\\b(?:password|pass|pwd|secret|token|api[_-]?token|apikey|client[_-]?secret|access[_-]?token|credential)\\s*=\\s*['\"][^'\"]{4,}['\"][^)]*\\)"
  severity: MEDIUM

- id: db.connection.string
  message: Database or connection string
  pattern: "(?i)\\b(?:mongodb_url|mongodb_uri|mongo_uri|mongo_url|connection_string|db_connection|database_url|dsn)\\s*[:=]\\s*['\"][^'\"]{4,}['\"]"
  severity: MEDIUM
